In [1]:
from gradio_client import Client   # for api use

import ast                         # for text to list conversion (make data useful)
import pandas as pd                # for easy data use; you can use polars or whatever you like

# start 8:14pm

# Accessing the API

Accessing the API is simple. You pass your key to the client, and then you will see a message the API has loaded.

In [2]:
token = '../api_creds/vi_key_1.csv'

# load my key
df = pd.read_csv(token) # easy and lazy lol; using pandas anyway ;p
api_key = df['key'][0]  # easy and lazy lol; using pandas anyway ;p

# connect to api
client = Client("verdantdavid/grooveseeker-feeds", token=api_key)

Loaded as API: https://verdantdavid-grooveseeker-feeds.hf.space

In [3]:
# search parameters
location = "Michigan"
start_date = "2026-09-01"
end_date = "2026-09-30"

In [4]:
feeds = client.predict(api_name="/discover_feeds")

feeds

['discover_feeds',
 'search_events',
 'search_event_prices',
 'search_locations',
 'search_entities',
 'search_entity_events',
 'search_entity_event_prices',
 'search_entity_collaborations',
 'search_websites',
 'search_website_entities',
 'search_website_events',
 'search_country_counts']

In [134]:
#location = 'San Francisco'

api_name = "/search_events"

results = client.predict(location=location, start_date=start_date, end_date=end_date, api_name=api_name)

df = pd.DataFrame(results)

df.head(100)

,event_date,event_title,event_text
0,2026-09-30T08:45:00.000000000+00:00,55+ Drop-In Hockey,55+ Drop-In Hockey\n\nPerformers:\nNot provide...
1,2026-09-30T00:00:00.000000000+00:00,Taking the Long Way 20th Anniversary Tour,Taking the Long Way 20th Anniversary Tour\n\nP...
2,2026-09-28T08:45:00.000000000+00:00,55+ Drop-In Hockey,55+ Drop-In Hockey\n\nPerformers:\nNot provide...
3,2026-09-27T14:00:00.000000000+00:00,Oktoberfest: A Queer Afternoon at Dakota Inn R...,Oktoberfest: A Queer Afternoon at Dakota Inn R...
4,2026-09-26T18:00:00.000000000+00:00,Endless Summer Gala 2026,Endless Summer Gala 2026\n\nPerformers:\nFunkl...
...,...,...,...
91,2026-09-01T19:00:00.000000000+00:00,Huron Valley Harmonizers Chapter of the Barber...,Huron Valley Harmonizers Chapter of the Barber...
92,2026-09-01T19:00:00.000000000+00:00,Ann Arbor Camera Club,Ann Arbor Camera Club\n\nPerformers:\nNot prov...
93,2026-09-01T11:00:00.000000000+00:00,Family Storytime,Family Storytime\n\nPerformers:\nNot provided ...
94,2026-09-01T10:00:00.000000000+00:00,Blake's 2026 Annual Sunflower Festival,Blake's 2026 Annual Sunflower Festival\n\nPerf...
95,2026-09-01T00:00:00.000000000+00:00,Franke Center Fall Student Classes,Franke Center Fall Student Classes\n\nPerforme...

In [135]:
api_name = "/search_event_prices"

results = client.predict(location=location, start_date=start_date, end_date=end_date, api_name=api_name)

df = pd.DataFrame(results)

df.head(10)

,event_date,event_title,event_price,entities
0,2026-09-30T08:45:00.000000000+00:00,55+ Drop-In Hockey,$10.00 for skaters; $0.00 for goalies,[810 Sports Complex]
1,2026-09-28T08:45:00.000000000+00:00,55+ Drop-In Hockey,"$10.00 for skaters, $0.00 for goalies",[810 Sports Complex]
2,2026-09-27T14:00:00.000000000+00:00,Oktoberfest: A Queer Afternoon at Dakota Inn R...,$10.00,"[Dakota Inn Rathskeller, Samuel KO]"
3,2026-09-26T18:00:00.000000000+00:00,Endless Summer Gala 2026,Individual Tickets – $200; Sponsored Table of ...,"[West Michigan Symphony, The Beach Boys, Maris..."
4,2026-09-25T20:00:00.000000000+00:00,Jo Koy Stand-Up Performance,"Starting at $59, plus fees","[Jo Koy, FireKeepers Event Center, FireKeepers..."
5,2026-09-25T19:00:00.000000000+00:00,Jalasat: A Pop-Up Performance Series #11,Free with RSVP,[Arab American National Museum]
6,2026-09-24T19:00:00.000000000+00:00,Tales from the Archives: President Ford & Holland,"Free for members, $10 for non-members","[Holland Museum, Zeeland Historical Society, D..."
7,2026-09-24T11:30:00.000000000+00:00,810 Freestyle,$50,[810 Sports Complex]
8,2026-09-23T11:30:00.000000000+00:00,55+ Open Skate,$6.00,[810 Sports Complex]
9,2026-09-22T11:30:00.000000000+00:00,810 Freestyle,$15.00 +$0.38 ticket service fee,[810 Sports Complex]

In [136]:
api_name = "/search_locations"

results = client.predict(api_name=api_name)

df = pd.DataFrame(results)

df.head(10)

             location
0            A Coruña
1              Aachen
2             Aalborg
3               Aalen
4  Aalener Innenstadt
5               Aarau
6             Aarburg
7              Aargau
8              Aarhus
9    Abbey Brauweiler

In [137]:
api_name = "/search_entities"

results = client.predict(location=location, start_date=start_date, end_date=end_date, api_name=api_name)

df = pd.DataFrame(results)

df.head(10)

                            event_date                             entity
0  2026-09-30T08:45:00.000000000+00:00                 810 Sports Complex
1  2026-09-30T00:00:00.000000000+00:00                        Fox Theatre
2  2026-09-30T00:00:00.000000000+00:00                         The Chicks
3  2026-09-28T08:45:00.000000000+00:00                 810 Sports Complex
4  2026-09-27T14:00:00.000000000+00:00             Dakota Inn Rathskeller
5  2026-09-27T14:00:00.000000000+00:00                          Samuel KO
6  2026-09-26T18:00:00.000000000+00:00             West Michigan Symphony
7  2026-09-26T18:00:00.000000000+00:00                     The Beach Boys
8  2026-09-26T18:00:00.000000000+00:00                        Maris Myers
9  2026-09-26T18:00:00.000000000+00:00  VanDyk Mortgage Convention Center

In [138]:
api_name = "/search_entity_events"

results = client.predict(location=location, start_date=start_date, end_date=end_date, api_name=api_name)

df = pd.DataFrame(results)

df.head(10)

,event_date,entity,event_title
0,2026-09-30T08:45:00.000000000+00:00,810 Sports Complex,55+ Drop-In Hockey
1,2026-09-30T00:00:00.000000000+00:00,Fox Theatre,Taking the Long Way 20th Anniversary Tour
2,2026-09-30T00:00:00.000000000+00:00,The Chicks,Taking the Long Way 20th Anniversary Tour
3,2026-09-28T08:45:00.000000000+00:00,810 Sports Complex,55+ Drop-In Hockey
4,2026-09-27T14:00:00.000000000+00:00,Dakota Inn Rathskeller,Oktoberfest: A Queer Afternoon at Dakota Inn R...
5,2026-09-27T14:00:00.000000000+00:00,Samuel KO,Oktoberfest: A Queer Afternoon at Dakota Inn R...
6,2026-09-26T18:00:00.000000000+00:00,West Michigan Symphony,Endless Summer Gala 2026
7,2026-09-26T18:00:00.000000000+00:00,The Beach Boys,Endless Summer Gala 2026
8,2026-09-26T18:00:00.000000000+00:00,Maris Myers,Endless Summer Gala 2026
9,2026-09-26T18:00:00.000000000+00:00,VanDyk Mortgage Convention Center,Endless Summer Gala 2026

In [139]:
api_name = "/search_entity_event_prices"

results = client.predict(location=location, start_date=start_date, end_date=end_date, api_name=api_name)

df = pd.DataFrame(results)

df.head(10)

,event_date,entity,event_title,event_price
0,2026-09-30T08:45:00.000000000+00:00,810 Sports Complex,55+ Drop-In Hockey,$10.00 for skaters; $0.00 for goalies
1,2026-09-28T08:45:00.000000000+00:00,810 Sports Complex,55+ Drop-In Hockey,"$10.00 for skaters, $0.00 for goalies"
2,2026-09-27T14:00:00.000000000+00:00,Dakota Inn Rathskeller,Oktoberfest: A Queer Afternoon at Dakota Inn R...,$10.00
3,2026-09-27T14:00:00.000000000+00:00,Samuel KO,Oktoberfest: A Queer Afternoon at Dakota Inn R...,$10.00
4,2026-09-26T18:00:00.000000000+00:00,West Michigan Symphony,Endless Summer Gala 2026,Individual Tickets – $200; Sponsored Table of ...
5,2026-09-26T18:00:00.000000000+00:00,The Beach Boys,Endless Summer Gala 2026,Individual Tickets – $200; Sponsored Table of ...
6,2026-09-26T18:00:00.000000000+00:00,Maris Myers,Endless Summer Gala 2026,Individual Tickets – $200; Sponsored Table of ...
7,2026-09-26T18:00:00.000000000+00:00,VanDyk Mortgage Convention Center,Endless Summer Gala 2026,Individual Tickets – $200; Sponsored Table of ...
8,2026-09-26T18:00:00.000000000+00:00,Funkle Jessie,Endless Summer Gala 2026,Individual Tickets – $200; Sponsored Table of ...
9,2026-09-25T20:00:00.000000000+00:00,Jo Koy,Jo Koy Stand-Up Performance,"Starting at $59, plus fees"

In [140]:
api_name = "/search_entity_collaborations"

results = client.predict(location=location, start_date=start_date, end_date=end_date, api_name=api_name)

df = pd.DataFrame(results)

df.head(10)

,event_date,entity,event_title
0,2026-09-30,810 Sports Complex,55+ Drop-In Hockey
1,2026-09-30,Franke Center for the Arts,Franke Center Fall Student Classes
2,2026-09-30,Jocelyn France,Franke Center Fall Student Classes
3,2026-09-30,Rob Monahan,Franke Center Fall Student Classes
4,2026-09-30,Fox Theatre,Taking the Long Way 20th Anniversary Tour
5,2026-09-30,The Chicks,Taking the Long Way 20th Anniversary Tour
6,2026-09-28,810 Sports Complex,55+ Drop-In Hockey
7,2026-09-28,Main Street Area Association,A2 Summer Streets Music Series: Main Street Ar...
8,2026-09-28,A2 Summer Streets Music Series,A2 Summer Streets Music Series: Main Street Ar...
9,2026-09-28,Local musicians,A2 Summer Streets Music Series: Main Street Ar...

In [141]:
api_name = "/search_websites"

results = client.predict(location=location, start_date=start_date, end_date=end_date, api_name=api_name)

df = pd.DataFrame(results)

df.head(10)

                            event_date                   website  event_count
0  2026-09-30T08:45:00.000000000+00:00      810sportscomplex.com            1
1  2026-09-30T00:00:00.000000000+00:00          bostonherald.com            1
2  2026-09-28T08:45:00.000000000+00:00      810sportscomplex.com            1
3  2026-09-27T14:00:00.000000000+00:00          sickening.events            1
4  2026-09-26T18:00:00.000000000+00:00  westmichigansymphony.org            1
5  2026-09-25T20:00:00.000000000+00:00   battlecreekenquirer.com            1
6  2026-09-25T19:00:00.000000000+00:00    arabamericanmuseum.org            1
7  2026-09-25T00:00:00.000000000+00:00        michiganpublic.org            1
8  2026-09-24T20:00:00.000000000+00:00           ticketsignup.io            2
9  2026-09-24T19:30:00.000000000+00:00           detroitnews.com            1

In [142]:
api_name = "/search_website_entities"

results = client.predict(location=location, start_date=start_date, end_date=end_date, api_name=api_name)

df = pd.DataFrame(results)

df.head(10)

,event_date,website,entity
0,2026-09-30T08:45:00.000000000+00:00,810sportscomplex.com,810 Sports Complex
1,2026-09-30T00:00:00.000000000+00:00,bostonherald.com,Fox Theatre
2,2026-09-30T00:00:00.000000000+00:00,bostonherald.com,The Chicks
3,2026-09-28T08:45:00.000000000+00:00,810sportscomplex.com,810 Sports Complex
4,2026-09-27T14:00:00.000000000+00:00,sickening.events,Dakota Inn Rathskeller
5,2026-09-27T14:00:00.000000000+00:00,sickening.events,Samuel KO
6,2026-09-26T18:00:00.000000000+00:00,westmichigansymphony.org,West Michigan Symphony
7,2026-09-26T18:00:00.000000000+00:00,westmichigansymphony.org,The Beach Boys
8,2026-09-26T18:00:00.000000000+00:00,westmichigansymphony.org,Maris Myers
9,2026-09-26T18:00:00.000000000+00:00,westmichigansymphony.org,VanDyk Mortgage Convention Center

In [143]:
api_name = "/search_website_events"

results = client.predict(location=location, start_date=start_date, end_date=end_date, api_name=api_name)

df = pd.DataFrame(results)

df.head(10)

,event_date,website,event_title
0,2026-09-30T08:45:00.000000000+00:00,810sportscomplex.com,55+ Drop-In Hockey
1,2026-09-30T00:00:00.000000000+00:00,bostonherald.com,Taking the Long Way 20th Anniversary Tour
2,2026-09-28T08:45:00.000000000+00:00,810sportscomplex.com,55+ Drop-In Hockey
3,2026-09-27T14:00:00.000000000+00:00,sickening.events,Oktoberfest: A Queer Afternoon at Dakota Inn R...
4,2026-09-26T18:00:00.000000000+00:00,westmichigansymphony.org,Endless Summer Gala 2026
5,2026-09-25T20:00:00.000000000+00:00,battlecreekenquirer.com,Jo Koy Stand-Up Performance
6,2026-09-25T19:00:00.000000000+00:00,arabamericanmuseum.org,Jalasat: A Pop-Up Performance Series #11
7,2026-09-25T00:00:00.000000000+00:00,michiganpublic.org,The Coney
8,2026-09-24T20:00:00.000000000+00:00,ticketsignup.io,Nite Lites Halloween Drive Thru
9,2026-09-24T20:00:00.000000000+00:00,ticketsignup.io,Nite Lites Halloween Train 2026

In [144]:
api_name = "/search_country_counts"

results = client.predict(start_date=start_date, end_date=end_date, api_name=api_name)

df = pd.DataFrame(results)

df.head(10)

          country  event_count
0   United States         3656
1  United Kingdom          526
2         Germany          445
3          Canada          208
4           Italy           99
5          France           88
6         Ireland           75
7         Romania           49
8         Georgia           47
9           Spain           44

# MCP Examples

In [145]:
from mcp import ClientSession
from mcp.client.streamable_http import streamablehttp_client

import json

MCP_ENDPOINT = "https://verdantdavid-grooveseeker-feeds.hf.space/gradio_api/mcp/"
HEADERS = {"Authorization": "Bearer {}".format(api_key)}

In [146]:
async def call_feed(tool_name, **arguments):

    tool_name = "grooveseeker_feeds_{}".format(tool_name)

    async with streamablehttp_client(MCP_ENDPOINT, headers=HEADERS) as (read, write, _):
        async with ClientSession(read, write) as session:
            await session.initialize()

            result = await session.call_tool(
                tool_name,
                arguments=arguments
            )

            return "\n".join(
                block.text
                for block in result.content
                if block.type == "text"
            )

In [147]:
async def list_tools():

    async with streamablehttp_client(MCP_ENDPOINT, headers=HEADERS) as (read, write, _):
        async with ClientSession(read, write) as session:
            await session.initialize()

            result = await session.list_tools()

            return [tool.name for tool in result.tools]

In [148]:
tools = await list_tools()
tools = sorted(tools)
tools

['grooveseeker_feeds_discover_feeds',
 'grooveseeker_feeds_search_country_counts',
 'grooveseeker_feeds_search_entities',
 'grooveseeker_feeds_search_entity_collaborations',
 'grooveseeker_feeds_search_entity_event_prices',
 'grooveseeker_feeds_search_entity_events',
 'grooveseeker_feeds_search_event_prices',
 'grooveseeker_feeds_search_events',
 'grooveseeker_feeds_search_locations',
 'grooveseeker_feeds_search_website_entities',
 'grooveseeker_feeds_search_website_events',
 'grooveseeker_feeds_search_websites']

In [149]:
tool_name = "discover_feeds"

result = await call_feed(tool_name)
result = sorted(ast.literal_eval(result))

print(result)

['discover_feeds', 'search_country_counts', 'search_entities', 'search_entity_collaborations', 'search_entity_event_prices', 'search_entity_events', 'search_event_prices', 'search_events', 'search_locations', 'search_website_entities', 'search_website_events', 'search_websites']

In [150]:
tool_name = "search_country_counts"

result = await call_feed(tool_name)

df = pd.DataFrame(ast.literal_eval(result))

df.head(10)

          country  event_count
0   United States         1563
1         Germany          486
2  United Kingdom          226
3          Canada          137
4           Italy           83
5         Romania           72
6         Hungary           64
7          France           41
8           India           41
9     Switzerland           26

In [151]:
tool_name = "search_entities"

result = await call_feed(tool_name, location=location, start_date=start_date, end_date=end_date)

df = pd.DataFrame(ast.literal_eval(result))

df.head(10)

                            event_date                             entity
0  2026-09-30T08:45:00.000000000+00:00                 810 Sports Complex
1  2026-09-30T00:00:00.000000000+00:00                        Fox Theatre
2  2026-09-30T00:00:00.000000000+00:00                         The Chicks
3  2026-09-28T08:45:00.000000000+00:00                 810 Sports Complex
4  2026-09-27T14:00:00.000000000+00:00             Dakota Inn Rathskeller
5  2026-09-27T14:00:00.000000000+00:00                          Samuel KO
6  2026-09-26T18:00:00.000000000+00:00             West Michigan Symphony
7  2026-09-26T18:00:00.000000000+00:00                     The Beach Boys
8  2026-09-26T18:00:00.000000000+00:00                        Maris Myers
9  2026-09-26T18:00:00.000000000+00:00  VanDyk Mortgage Convention Center

In [152]:
tool_name = "search_entity_collaborations"

result = await call_feed(tool_name, location=location, start_date=start_date, end_date=end_date)

df = pd.DataFrame(ast.literal_eval(result))

df.head(10)

,event_date,entity,event_title
0,2026-09-30,810 Sports Complex,55+ Drop-In Hockey
1,2026-09-30,Franke Center for the Arts,Franke Center Fall Student Classes
2,2026-09-30,Jocelyn France,Franke Center Fall Student Classes
3,2026-09-30,Rob Monahan,Franke Center Fall Student Classes
4,2026-09-30,Fox Theatre,Taking the Long Way 20th Anniversary Tour
5,2026-09-30,The Chicks,Taking the Long Way 20th Anniversary Tour
6,2026-09-28,810 Sports Complex,55+ Drop-In Hockey
7,2026-09-28,Main Street Area Association,A2 Summer Streets Music Series: Main Street Ar...
8,2026-09-28,A2 Summer Streets Music Series,A2 Summer Streets Music Series: Main Street Ar...
9,2026-09-28,Local musicians,A2 Summer Streets Music Series: Main Street Ar...

In [153]:
tool_name = "search_entity_events"

result = await call_feed(tool_name, location=location, start_date=start_date, end_date=end_date)

df = pd.DataFrame(ast.literal_eval(result))

df.head(10)

,event_date,entity,event_title
0,2026-09-30T08:45:00.000000000+00:00,810 Sports Complex,55+ Drop-In Hockey
1,2026-09-30T00:00:00.000000000+00:00,Fox Theatre,Taking the Long Way 20th Anniversary Tour
2,2026-09-30T00:00:00.000000000+00:00,The Chicks,Taking the Long Way 20th Anniversary Tour
3,2026-09-28T08:45:00.000000000+00:00,810 Sports Complex,55+ Drop-In Hockey
4,2026-09-27T14:00:00.000000000+00:00,Dakota Inn Rathskeller,Oktoberfest: A Queer Afternoon at Dakota Inn R...
5,2026-09-27T14:00:00.000000000+00:00,Samuel KO,Oktoberfest: A Queer Afternoon at Dakota Inn R...
6,2026-09-26T18:00:00.000000000+00:00,West Michigan Symphony,Endless Summer Gala 2026
7,2026-09-26T18:00:00.000000000+00:00,The Beach Boys,Endless Summer Gala 2026
8,2026-09-26T18:00:00.000000000+00:00,Maris Myers,Endless Summer Gala 2026
9,2026-09-26T18:00:00.000000000+00:00,VanDyk Mortgage Convention Center,Endless Summer Gala 2026

In [154]:
tool_name = "search_entity_event_prices"

result = await call_feed(tool_name, location=location, start_date=start_date, end_date=end_date)

df = pd.DataFrame(ast.literal_eval(result))

df.head(10)

,event_date,entity,event_title,event_price
0,2026-09-30T08:45:00.000000000+00:00,810 Sports Complex,55+ Drop-In Hockey,$10.00 for skaters; $0.00 for goalies
1,2026-09-28T08:45:00.000000000+00:00,810 Sports Complex,55+ Drop-In Hockey,"$10.00 for skaters, $0.00 for goalies"
2,2026-09-27T14:00:00.000000000+00:00,Dakota Inn Rathskeller,Oktoberfest: A Queer Afternoon at Dakota Inn R...,$10.00
3,2026-09-27T14:00:00.000000000+00:00,Samuel KO,Oktoberfest: A Queer Afternoon at Dakota Inn R...,$10.00
4,2026-09-26T18:00:00.000000000+00:00,West Michigan Symphony,Endless Summer Gala 2026,Individual Tickets – $200; Sponsored Table of ...
5,2026-09-26T18:00:00.000000000+00:00,The Beach Boys,Endless Summer Gala 2026,Individual Tickets – $200; Sponsored Table of ...
6,2026-09-26T18:00:00.000000000+00:00,Maris Myers,Endless Summer Gala 2026,Individual Tickets – $200; Sponsored Table of ...
7,2026-09-26T18:00:00.000000000+00:00,VanDyk Mortgage Convention Center,Endless Summer Gala 2026,Individual Tickets – $200; Sponsored Table of ...
8,2026-09-26T18:00:00.000000000+00:00,Funkle Jessie,Endless Summer Gala 2026,Individual Tickets – $200; Sponsored Table of ...
9,2026-09-25T20:00:00.000000000+00:00,Jo Koy,Jo Koy Stand-Up Performance,"Starting at $59, plus fees"

In [155]:
tool_name = "search_event_prices"

result = await call_feed(tool_name, location=location, start_date=start_date, end_date=end_date)

df = pd.DataFrame(ast.literal_eval(result))

df.head(10)

,event_date,event_title,event_price,entities
0,2026-09-30T08:45:00.000000000+00:00,55+ Drop-In Hockey,$10.00 for skaters; $0.00 for goalies,[810 Sports Complex]
1,2026-09-28T08:45:00.000000000+00:00,55+ Drop-In Hockey,"$10.00 for skaters, $0.00 for goalies",[810 Sports Complex]
2,2026-09-27T14:00:00.000000000+00:00,Oktoberfest: A Queer Afternoon at Dakota Inn R...,$10.00,"[Dakota Inn Rathskeller, Samuel KO]"
3,2026-09-26T18:00:00.000000000+00:00,Endless Summer Gala 2026,Individual Tickets – $200; Sponsored Table of ...,"[West Michigan Symphony, The Beach Boys, Maris..."
4,2026-09-25T20:00:00.000000000+00:00,Jo Koy Stand-Up Performance,"Starting at $59, plus fees","[Jo Koy, FireKeepers Event Center, FireKeepers..."
5,2026-09-25T19:00:00.000000000+00:00,Jalasat: A Pop-Up Performance Series #11,Free with RSVP,[Arab American National Museum]
6,2026-09-24T19:00:00.000000000+00:00,Tales from the Archives: President Ford & Holland,"Free for members, $10 for non-members","[Holland Museum, Zeeland Historical Society, D..."
7,2026-09-24T11:30:00.000000000+00:00,810 Freestyle,$50,[810 Sports Complex]
8,2026-09-23T11:30:00.000000000+00:00,55+ Open Skate,$6.00,[810 Sports Complex]
9,2026-09-22T11:30:00.000000000+00:00,810 Freestyle,$15.00 +$0.38 ticket service fee,[810 Sports Complex]

In [156]:
tool_name = "search_events"

result = await call_feed(tool_name, location=location, start_date=start_date, end_date=end_date)

df = pd.DataFrame(ast.literal_eval(result))

df.head(10)

,event_date,event_title,event_text
0,2026-09-30T08:45:00.000000000+00:00,55+ Drop-In Hockey,55+ Drop-In Hockey\n\nPerformers:\nNot provide...
1,2026-09-30T00:00:00.000000000+00:00,Taking the Long Way 20th Anniversary Tour,Taking the Long Way 20th Anniversary Tour\n\nP...
2,2026-09-28T08:45:00.000000000+00:00,55+ Drop-In Hockey,55+ Drop-In Hockey\n\nPerformers:\nNot provide...
3,2026-09-27T14:00:00.000000000+00:00,Oktoberfest: A Queer Afternoon at Dakota Inn R...,Oktoberfest: A Queer Afternoon at Dakota Inn R...
4,2026-09-26T18:00:00.000000000+00:00,Endless Summer Gala 2026,Endless Summer Gala 2026\n\nPerformers:\nFunkl...
5,2026-09-25T20:00:00.000000000+00:00,Jo Koy Stand-Up Performance,Jo Koy Stand-Up Performance\n\nPerformers:\nJo...
6,2026-09-25T19:00:00.000000000+00:00,Jalasat: A Pop-Up Performance Series #11,Jalasat: A Pop-Up Performance Series #11\n\nPe...
7,2026-09-25T00:00:00.000000000+00:00,The Coney,"The Coney\n\nPerformers:\nKristen Bell, Tim Me..."
8,2026-09-24T20:00:00.000000000+00:00,Nite Lites Halloween Drive Thru,Nite Lites Halloween Drive Thru\n\nPerformers:...
9,2026-09-24T20:00:00.000000000+00:00,Nite Lites Halloween Train 2026,Nite Lites Halloween Train 2026\n\nPerformers:...

In [157]:
tool_name = "search_locations"

result = await call_feed(tool_name)

df = pd.DataFrame(ast.literal_eval(result))

df.head(10)

             location
0            A Coruña
1              Aachen
2             Aalborg
3               Aalen
4  Aalener Innenstadt
5               Aarau
6             Aarburg
7              Aargau
8              Aarhus
9    Abbey Brauweiler

In [158]:
tool_name = "search_website_entities"

result = await call_feed(tool_name, location=location, start_date=start_date, end_date=end_date)

df = pd.DataFrame(ast.literal_eval(result))

df.head(10)

,event_date,website,entity
0,2026-09-30T08:45:00.000000000+00:00,810sportscomplex.com,810 Sports Complex
1,2026-09-30T00:00:00.000000000+00:00,bostonherald.com,Fox Theatre
2,2026-09-30T00:00:00.000000000+00:00,bostonherald.com,The Chicks
3,2026-09-28T08:45:00.000000000+00:00,810sportscomplex.com,810 Sports Complex
4,2026-09-27T14:00:00.000000000+00:00,sickening.events,Dakota Inn Rathskeller
5,2026-09-27T14:00:00.000000000+00:00,sickening.events,Samuel KO
6,2026-09-26T18:00:00.000000000+00:00,westmichigansymphony.org,West Michigan Symphony
7,2026-09-26T18:00:00.000000000+00:00,westmichigansymphony.org,The Beach Boys
8,2026-09-26T18:00:00.000000000+00:00,westmichigansymphony.org,Maris Myers
9,2026-09-26T18:00:00.000000000+00:00,westmichigansymphony.org,VanDyk Mortgage Convention Center

In [159]:
tool_name = "search_website_events"

result = await call_feed(tool_name, location=location, start_date=start_date, end_date=end_date)

df = pd.DataFrame(ast.literal_eval(result))

df.head(10)

,event_date,website,event_title
0,2026-09-30T08:45:00.000000000+00:00,810sportscomplex.com,55+ Drop-In Hockey
1,2026-09-30T00:00:00.000000000+00:00,bostonherald.com,Taking the Long Way 20th Anniversary Tour
2,2026-09-28T08:45:00.000000000+00:00,810sportscomplex.com,55+ Drop-In Hockey
3,2026-09-27T14:00:00.000000000+00:00,sickening.events,Oktoberfest: A Queer Afternoon at Dakota Inn R...
4,2026-09-26T18:00:00.000000000+00:00,westmichigansymphony.org,Endless Summer Gala 2026
5,2026-09-25T20:00:00.000000000+00:00,battlecreekenquirer.com,Jo Koy Stand-Up Performance
6,2026-09-25T19:00:00.000000000+00:00,arabamericanmuseum.org,Jalasat: A Pop-Up Performance Series #11
7,2026-09-25T00:00:00.000000000+00:00,michiganpublic.org,The Coney
8,2026-09-24T20:00:00.000000000+00:00,ticketsignup.io,Nite Lites Halloween Drive Thru
9,2026-09-24T20:00:00.000000000+00:00,ticketsignup.io,Nite Lites Halloween Train 2026